#  Deployment  & Service in one file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels: # label for  deployment is optional, but recommended.
    app: mongo
spec:
  replicas: 1 # how many pods using this blueprint.
  selector:
    matchLabels:
      app: mongo # Standard is using app, and the label name.
  template:
    metadata:
      labels: # For pods this is required.
        app: mongo 
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0 # We are using 5.0 image version.
        ports:
        - containerPort: 27017
---

# Service Configuration.

apiVersion: v1
kind: Service
metadata:
  name: mongo-service # This is name of the service, which is used to access mongo.
spec:
  selector: # Points to the Pod where this service belongs to.
    app: mongo # The label of the pod.
  ports:
    - protocol: TCP
      port: 9376 # Port of service. Standard these should be same.
      targetPort: 9376 # Port where to forward into. Standard these should be same.